# Generated by Django 4.0.1 on 2022-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phno', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'unique_together': {('email_id', 'phno')},
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
