# Generated by Django 4.0.1 on 2022-01-31 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_delete_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phno',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator]),
        ),
    ]
