# Generated by Django 4.0.1 on 2022-02-02 14:04

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_user_unique_together_alter_user_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phno',
            field=models.CharField(max_length=10, unique=True, validators=[userapp.models.phone_validator]),
        ),
    ]
